### POST request to create new patient
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Pearson Jess",
  "email": "testing@gmail.com",
  "address": "32nd setrand ave",
  "dateOfBirth": "1995-09-09",
  "registeredDate": "2024-11-28"
}

###